name: learning-german
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - python=3.9
  - spacy=3.2
  - google-cloud-translate=2.0.1
  - python-dotenv=0.19
  - streamlit=0.81
  - pip:
    - deep-translator==1.6.*
    - iso639==0.1.*
    - gtts==2.2.*
    - https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.2.0/en_core_web_sm-3.2.0-py3-none-any.whl
    - https://github.com/explosion/spacy-models/releases/download/de_core_news_sm-3.2.0/de_core_news_sm-3.2.0-py3-none-any.whl
    - https://github.com/explosion/spacy-models/releases/download/pt_core_news_sm-3.2.0/pt_core_news_sm-3.2.0-py3-none-any.whl
