name: learning-german
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - python=3.9
  - spacy=3.1
  - pip:
    - gtts==2.2.*
    - translate==3.6.*
    - https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.1.0/en_core_web_sm-3.1.0-py3-none-any.whl
    - https://github.com/explosion/spacy-models/releases/download/de_core_news_sm-3.1.0/de_core_news_sm-3.1.0-py3-none-any.whl
    - https://github.com/explosion/spacy-models/releases/download/pt_core_news_sm-3.2.0/pt_core_news_sm-3.2.0-py3-none-any.whl
